# basic
title: Azure Cert Preppies
subtitle: Azure 자격증 준비하기
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: avatar.png
banner_small: banner.png
banner_large: banner.png

# disqus
disqus_shortname: 

# social
social:
  github: justinyoo/azure-cert-prep
  twitter: WEIRDxMEETUP
  weibo: 

# nav #
nav:
  home: .
  archive: archives
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_analytics: UA-749520-7 # Put tracking ID here
